# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='article/cover', verbose_name='\u5c01\u9762')),
                ('type', models.IntegerField(choices=[(0, '\u8bfb\u4e66\u5fc3\u5f97'), (1, '\u597d\u4e66\u63a8\u8350')], default=0, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
    ]
